version: "3"
services:
    rosetta-ledgis:
        container_name: rosetta-ledgis
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./
        env_file: 
            - .env
        ports:
            - ${PORT}:8000