version: "3"
services:
    rosetta-ledgis:
        container_name: rosetta-ledgis
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - ${PORT}:8000